name: Check BingX Symbols
on: [push, workflow_dispatch]

jobs:
  check-symbols:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Python Script
        run: |
          python3 -c "import requests; headers = {'User-Agent': 'Mozilla/5.0'}; r = requests.get('https://open-api.bingx.com/openApi/swap/v2/market/symbols', headers=headers); print(r.json())"


